name: restaurant
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  android_alarm_manager_plus: ^3.0.4
  bloc: ^8.1.1
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^16.2.0
  flutter_map: ^5.0.0
  flutter_native_splash: ^2.3.5
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  google_fonts: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.0.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2
  lottie: ^2.6.0
  multi_image_picker_view: ^0.0.17
  package_info_plus: ^4.0.2
  page_transition: ^2.0.9
  path_provider: ^2.1.1
  permission_handler: ^10.4.3
  persistent_bottom_nav_bar_v2: ^4.2.8
  provider: ^6.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  syncfusion_flutter_datepicker: ^22.2.9

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.1

targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: true
          explicit_to_json: false

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter_native_splash:
  color: "#1E1E1E"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#1E1E1E"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/l10n/
